apiVersion: gitlab.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: gitlab-credentials
      namespace: crossplane-system
      key: credentials
  baseURL: <gitlab-instance-url>
